cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
  - build
  - test
  - package
  - deploy

build:
  image: ruby:2.6
  stage: build
  script:
    - apt update
    - apt-get install -y docker
    - gem install bundler foreman
    - apt-get install nodejs npm
    - npm install yarn -g
    - docker-compose up -d
    - cd backend && bundle install && cd ..
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - foreman start &
    - cd frontend && yarn start
