cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
  - build
  - test
  - package
  - deploy

build:
  image: docker
  stage: build
  script:
    - apt-get install software-properties-common
    - apt-add-repository -y ppa:rael-gc/rvm
    - apt-get update
    - apt-get install rvm
    - rvm install ruby-2.6.3
