cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
  - build
  - test
  - package
  - deploy

build:
  image: node
  stage: build
  script:
    - apt update -y
    - apt-get install software-properties-common -y
#    - apt-add-repository -y ppa:rael-gc/rvm
    - add-apt-repository 'deb http://ppa.launchpad.net/rael-gc/rvm/ubuntu disco main'
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7BE3E5681146FD4F1A40EDA28094BB14F4E3FBBE
    - apt update -y
    - apt-get install rvm -y
    - rvm install ruby-2.6.3
