cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
  - build
  - test
  - package
  - deploy

build:
  image: ruby:2.6
  stage: build
  script:
    - apt update
    - apt-get install -y docker
    - gem install bundler foreman
    - apt-get install nodejs npm -y
    - npm install yarn -g
    - curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose -f docker-compose.yml up -d
    - cd backend && bundle install && cd ..
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - foreman start &
    - cd frontend && yarn start
