cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
  - build
  - test
  - package
  - deploy

build:
  image: ruby:2.6
  stage: build
  script:
    - apt update
    - apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt update
    - apt install docker-ce docker-ce-cli containerd.io -y
    - gem install bundler foreman
    - apt-get install nodejs npm -y
    - npm install yarn -g
    - curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - service docker start
    - usermod -aG docker root
    - source /root/.bashrc
    - docker-compose -f docker-compose.yml up -d
    - cd backend && bundle install
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - foreman start &
    - cd ..
    - cd frontend && yarn start
